name: Pull changed translations from Lokalise

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          base_lang: en
          skip_original_filenames: true
          translations_path: |
            g11n/data/src/main/res/values-b+es+419
          file_format: xml
          flat_naming: true
          additional_params: >
            {
              "original_filenames": false,
              "bundle_structure": "g11n/data/src/main/res/values-b+es+419/strings.xml",
              "filter_langs": ["es"]
            }